baseURL = 'https://whatisthaodoing.today/'
languageCode = 'en'
defaultContentLanguage = "en"
title = 'Charlie Thao'
theme = "hution"
paginate = 10

enableEmoji = true
googleAnalystics = "G-D3P4E875CK"
pygmentsUseClasses = true

# Router
[permalinks]
post = "post/:title"

[params]
color = "#2E5A88"
customJS = ["/custom.js"]
customCSS = ["/code-style.css"]

mainSections = ["author/thao"]
favicon = "/img/favicon.png"

[taxonomies]
author = "author"
tag = "tags"
category = "categories"

[[params.nav]]
name = "About me"
url = "author/thao"
weight = 99

[[params.nav]]
name = "Projects"
url = "tags/projects"
weight = 1

[[params.nav]]
name = "Blog"
url = "post"
weight = 2

[[params.social]]
name = "github"
icon = "fab fa-2x fa-github"
url = "https://github.com/acapela000"

[[params.social]]
name = "linkedin"
icon = "fab fa-2x fa-linkedin"
url = "https://www.linkedin.com/in/truong-thao-98b647223/"